### ISSUE TITLE
easier way to create path?

### ISSUE THREAD

**Issue by amueller** [matplotlib/viscm#13]
I find it quite hard to use the gui, maybe because I haven't used it enough before. I was trying to create a colormap with endpoints FF0000 and 0000FF and didn't really manage.
It would be cool to have a copy-paste example to generate maybe even just a linear colormap. Or are linear colormaps not good? I typed up the stuff that Nathaniel showed in the talk for demonstrating colorspacious ("there is 100 years of color theory in this line"). If this is a reasonable way to do that, maybe just add the code as an example either here or in colorspacious?

If it is already there, I'm sorry, but I couldn't find it.

**Comment by njsmith** [comment]
"endpoints FF0000 and 0000FF" is in RGB-space, and viscm is not really designed for thinking in RGB space. (I'm not going to say you're necessarily wrong for wanting this, but OTOH the nudge to not-think-in-RGB-space is intentional :-).) Also the GUI (which is super unintuitive, yes :-)) is specifically designed for designing colormaps that meet the constraints described in the talk (linear lightness ramp, perceptually uniform), and these constraints are baked into the GUI itself. It may or may not even be possible to hit FF0000 and 0000FF while meeting these constraints, because they're on the edge of the gamut, and you may not be able to get from one to the other while staying within gamut etc.

Re: "linear colormap" -- not sure what you mean? You could use colorspacious to convert FF0000 and 0000FF to CAM02-UCS space, draw a line between them, and then map that line back to RGB, maybe?

**Comment by amueller** [comment]
By linear, I meant a line in the CAM02-UCS space.
I actually just tried the approach you were suggesting. I had two issues: converting back to RGB gave me values outside of (0, 1) (by 1e-14 or something), the other is that there are weird artifacts in the perceptual delta:

![ripples_colormap](https://cloud.githubusercontent.com/assets/449558/13583288/7506bdfe-e47e-11e5-9552-26b2ebf4bd49.png)

anyhow, I think I hit points close enough to what I wanted using viscm and I'm happy with the result.
I think perceptually uniform is a good assumption to bake in, and linear lightness a reasonable one.

This is an awesome tool btw.

**Comment by njsmith** [comment]
The perceptual delta ripples you can ignore -- those are just numerical artifacts.

The values outside of (0, 1) thing is also expected -- CAM02-UCS doesn't know anything about monitor limitations (the colors outside of (0, 1) are perfectly well-defined, it's just that your monitor is not flexible enough to show them), and then of course you're starting at the very edge of the space and getting floating point rounding error on top of that. You're lucky that all the points in between genuinely are in-gamut -- if you click the "toggle gamut" option there to visualize the space of colors that monitors can display, you'll notice that in CAM02-UCS space it isn't actually convex :-)

**Comment by amueller** [comment]
good to know, thanks! Not sure where but I think it would be nice if you put a sample script for making a colormap in the docs for either viscm ("visualizing a custom colormap") or colorspacious. It's not hard and only a couple of lines, as with your circular example.
You could add something on creating and then visualizing the circular colormap, I think that would help people that want to create their own, without using the creation gui.
[for example it's not quite clear how the `view` part works for me. does it use `cm_data` or `test_cm`?]

**Comment by amueller** [comment]
(quick test shows that it seems to look for `test_cm` but thats kind of non-obvious to me)

**Comment by njsmith** [comment]
Perhaps you would like to submit a PR? :-)

**Comment by amueller** [comment]
I should. Though the whole colormap thing was me nerd-sniping myself the second time within the last week. possibly procrastinating on making matplotlib figures render nicely in ipython notebook pdf export. which is really fun, I can tell you.

**Comment by njsmith** [comment]
If it weren't for procrastination I don't think I'd ever get anything done.

**Comment by njsmith** [comment]
I think this can be closed?

**Comment by amueller** [comment]
Yeah
