### ISSUE TITLE
Diverging colormap design

### ISSUE THREAD

**Issue by rkern** [matplotlib/viscm#4]
Kenneth Moreland (of [CoolWarm](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py#L1752-L1754) fame) gives an [algorithm for designing perceptual diverging colormaps](http://kennethmoreland.com/color-maps/) that should be straightforward to implement here. He uses CIELAB as the core perceptual colorspace, so it would be interesting to see it reimplemented with CAM02-UCS instead.

**Comment by njsmith** [comment]
FTR I think that @kthyng may also be working on extending the tool so it can be used to easily design diverging colormaps.

**Comment by kthyng** [comment]
Yes, still working on that (did some more today). My confusion with Moreland's coolwarm colormap is how narrow the range of lightness is. That property seems to wipe out a lot of detail that can be seen in maps over larger lightness ranges, but I suspect he chose it for a particular reason.

**Comment by njsmith** [comment]
For coolwarm, IIRC having a narrow range of lightness was an explicit
design goal, since they wanted a colormap that would be suitable for
overlaying on 3d-rendered objects, where you want to mostly reserve the
lightness channel for lighting/reflectance/shadow information that gives
you cues to shape. Different tools for different purposes, I guess...

On Wed, Jul 15, 2015 at 4:43 PM, Kristen Thyng notifications@github.com
wrote:

> Yes, still working on that (did some more today). My confusion with
> Moreland's coolwarm colormap is how narrow the range of lightness is. That
> property seems to wipe out a lot of detail that can be seen in maps over
> larger lightness ranges, but I suspect he chose it for a particular reason.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matplotlib/viscm/issues/4#issuecomment-121758967.

## 

Nathaniel J. Smith -- http://vorpus.org

**Comment by rkern** [comment]
Or the application of hill shading, to bring it back to a 2D application.

**Comment by kthyng** [comment]
Ok, got it.

**Comment by njsmith** [comment]
Current master now has support for designing diverging colormaps.
